etl:
  input_path: ###
  output_path: 'processed.parquet'
  stages: 
    [
      {name: "clean", ops: ["drop_nulls: age"]}, 
      {name: "window", ops: ["rolling_mean: {col: age, window: 5, over: user_id}"]}, 
      {name: "agg", ops: ["group_by: user_id, agg: {mean: mb_used}"]}
    ]

