data: 
  input_path: ###
  output_path: 'Escalado_datos'

compute:
  use_ray: false
  chunk_size: 1000000
  streaming: true
  partition_by: ["user_id"]

ml:
  learning_rate: 0.01
  scaler: "minmax"
  feature_columns: ["age"]
  aggregations:
    age: "sum"
