compute:
  use_ray: true
  chunk_size: 10000
  streaming: true
  memory_limit: "2GB"
  partition_by: ["user_id"]
etl:
  input_paths: [###]
  output_path: "joined.parquet"
  join_on: "user_id"
  join_type: "inner"
  column_filter: "mb_used"
