compute:
  use_ray: true
  chunk_size: 10000
  streaming: true
  memory_limit: "2GB"
  partition_by: ["user_id"]
etl:
  input_paths: ["/home/arbolitos7/Documents/ArbolitosMiCasita/SeaAndFishes/LakeLife_Toml_Prefect/Ejercicos_Intermedio_DaskPolars/V1.01/megaline_internet.csv", "/home/arbolitos7/Documents/ArbolitosMiCasita/SeaAndFishes/LakeLife_Toml_Prefect/Ejercicios_Intermedio/megaline_users.csv"]
  output_path: "joined.parquet"
  join_on: "user_id"
  join_type: "inner"
  column_filter: "mb_used"